### ISSUE TITLE
Negative test suite timing

### ISSUE THREAD

**Issue by supernomad** [jest-community/jest-junit#103]
I am currently seeing some issues running jest with the jest-junit reporter. I am getting a junit xml file back that is properly formatted but contains invalid data for instance I am seeing this:

```xml
<testsuite name="src/__tests__/Example.test.js" errors="0" failures="0" skipped="1" timestamp="2019-10-02T21:35:57" time="-11770557.774" tests="1">
    <testcase classname="Example thing" name="Example thing" time="0.001">
      <skipped/>
    </testcase>
  </testsuite>
```
Notice the `time="-11770557.774"` bit and the fact that it can't possible have a negative number for the amount of time a test took.

This is just one example and at fist I thought it was just because the test was skipped and the timing was so close that the logic resulted in a rounding error or something similar. However it also appears on tests that are successful/failed.

That being said I looked at the code specifically this line: https://github.com/jest-community/jest-junit/blob/v8.0.0/utils/buildJsonResults.js#L84 and based on this logic it seems that the `suite.perfStats.end` is equal to `0` otherwise I have no idea why/how the resulting return from the `executionTime` function could ever really be negative.

I am not 100% certain this is an issue with the jest-junit or if the issue is really with jest itself, but I can't find any existing issues referencing this. Any guidance would be extremely helpful.

Version Details:
- jest: 24.7.1
- jest-junit: 8.0.0
- jest-dom: 4.0.0
- jest-environment-jsdom-fourteen 0.1.0
- jest-resolve 24.7.1
- jest-watch-typeahead 0.3.0

**Comment by palmerj3** [comment]
@supernomad thanks for reporting! This is the first time I've heard of this happening.

Could you please create a repository that reproduces this issue and link to it in this thread?

I'll need that in order to investigate this.

**Comment by supernomad** [comment]
Unfortunately I have no time to do that, and this particular bug is rather perplexing I manually edited the module locally with the change proposed in the attached PR and this problem has effectively gone away. Although not ideal I do not believe that this particular bug is within jest-junit but jest itself or some combination there of.

**Comment by supernomad** [comment]
this ended up being due to an erroneous jest mock of the `Date.now` function :man_facepalming:
