### ISSUE TITLE
reporter options are blitzed if one of the properties of the options object is a function

### ISSUE THREAD

**Issue by dagda1** [jest-community/jest-junit#105]
If I pass these options based on the example in the README

```javascript
// jest.config.js
{
  reporters: [
    "default",
      [
        "jest-junit",
        {
          a: 'b',
          classNameTemplate: (vars) => {
            throw new Error('fook');
            return vars.classname.toUpperCase();
          }
        }
      ]
  ]
}
```

And I log the options in the `JestJunit` constructor function, it logs this:
```javascript
[ [ 'default', {} ],
  [ '/Users/developer15/projects/scot.disclosure.digital-frontend/node_modules/jest-junit/index.js',
    { a: 'b' } ] ]
```

So the function gets blitzed because I guess `JSON.stringify` is called somewhere.

Did this ever work?

**Comment by palmerj3** [comment]
Thanks for reporting! I can have a look tomorrow and see. It should be working - we do have a test to make sure this continues to work.

https://github.com/jest-community/jest-junit/blob/master/__tests__/buildJsonResults.test.js#L58

But I will take a deeper dive tomorrow and try to give you more info.

**Comment by dagda1** [comment]
@palmerj3 thank you so much.

I don't think that test will help, you are directly merging in the `classNameTemplate` function.  This is almost like it is happening before it actually gets to the `JestJunit` constructor function.

If you look at my report above, something is happening between jest reading my projects `jest.confg` and it reaching the `JestJunit` constructor function.  

Your test will always pass but I think jest might be calling `JSON.stringify` in the config

**Comment by dagda1** [comment]
@palmerj3 I just created a test repo for this bug and found out it is not a bug :).  I hope I have not wasted any of your time

**Comment by palmerj3** [comment]
No worries thanks for doing that! Take care.
