### ISSUE TITLE
Is there a good way to use this with projects?

### ISSUE THREAD

**Issue by bencooper222** [jest-community/jest-junit#106]
This reporter works with the jest projects array but all that happens is the last project to run overwrites the file. I'd either like it to append to the original file or create separate files. Is there a way to do this?

**Comment by palmerj3** [comment]
Can you provide a sample repo that shows this happening?

jest-junit has been used in multi-project environments and I haven't heard of the junit.xml file being overwritten.

**Comment by andrcuns** [comment]
@bencooper222 as per discussion in #108, if You have multiple projects, You simply need to prefix test run command with appropriate env variable, `JEST_JUNIT_OUTPUT_NAME=project_1.xml npm test...`, `JEST_JUNIT_OUTPUT_NAME=project_2.xml npm test...` so each run generates it's own xml file.

**Comment by bencooper222** [comment]
ahhhh thanks so much @andrcuns

**Comment by t-shreysingh** [comment]
I have used this command to create junit.xml and it is successfully creating junit.xml file

jest --ci --reporters=default --reporters=jest-junit
But when I'm using this command to create a junit file with different name it is giving me an error. The command is
JEST_JUNIT_OUTPUT_NAME="file.xml" jest
error: 'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command,
operable program or batch file.
The version of jest is: 27.3.1
"jest-junit": "^16.0.0"
@andrcuns Can you help me out?

**Comment by t-shreysingh** [comment]
I have tried this also. 
C:\Users\t-shreysingh\Downloads\jestfile-2\JEST(COPY)>JEST_JUNIT_OUTPUT_NAME=project_1.xml npm test...
'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command,
operable program or batch file.
@andrcuns
