### ISSUE TITLE
jest-junit hangs jest if not executed from the project root

### ISSUE THREAD

**Issue by andreabisello** [jest-community/jest-junit#107]
on a updated windows 10 64bit,
with node 10.16.3,
with jest 1.20,

with a very simple test
```

describe('Generic Test', () => {

    test("test1", () => {
        expect(2).toBe(2)
    })

});

```
with this jest.config.js file

```

    module.exports = {
        preset: "jest-puppeteer",
        setupFilesAfterEnv: [  // NOT setupFiles
            "./custom-configuration.js"
        ],
        reporters: ["default","jest-junit"]
    };

```
if i run "jest" from the root of the project, 

test pass and jest quit creating the xml.

if i run from external path, jest pass the test, then it hangs.

>jest --config c:\src\e2e\jest.config.js --rootDir c:\src\e2e\ 

![image](https://user-images.githubusercontent.com/2149815/67023881-cc856180-f103-11e9-926d-a15146529e82.png)

the problem is related with the reporter,

if i remove the reporter,

everything works.

any suggestion?

thanks.

**Comment by palmerj3** [comment]
Thanks for reporting!

Let me see if I can reproduce this locally..

**Comment by andreabisello** [comment]
i think the problem is related to some writing permission on c:\, because https://www.npmjs.com/package/jest-bamboo-reporter warns me about the reporter cannot create the xml on c:\ , but jest-junit hangs.

can you try on a windows machine?

so i tried moving on another folder, but nothing changed.

it works only if i run jest from the repository folder.

tomorrow i will share a repository.

**Comment by palmerj3** [comment]
I don't have access to a windows machine

**Comment by palmerj3** [comment]
On my local machine I set the working directory to read only so it wouldn't be able to write the junit.xml file. It does not hang and it errors out with the error:

`Error: EACCES: permission denied, open '/Users/jpalmer/Desktop/test/junit.xml'
`

**Comment by andreabisello** [comment]
@palmerj3 
this is the repository
https://github.com/andreabisello/jest-junit-example

clone it, run npm install, run jest from the project root.
then move on c:\ and run

C:\>jest --config C:\src\jest-junit-example\jest.config.js --rootDir C:\src\jest-junit-example\

![image](https://user-images.githubusercontent.com/2149815/67072147-8b816180-f184-11e9-91ce-484b30b6d92f.png)

it hangs.

this weekend i will try on another windows pc.

**Comment by palmerj3** [comment]
Thank you!

Unfortunately I still get the exact same behavior: an immediate error that i'm unable to write junit.xml.

Definitely going to need more information from you about your machine configuration before i can consider this a bug and investigate further.

**Comment by andreabisello** [comment]
@palmerj3 my home computer has the same problem of the work computer

![image](https://user-images.githubusercontent.com/2149815/67145624-311afa80-f283-11e9-807c-22b09bb1f90d.png)


![image](https://user-images.githubusercontent.com/2149815/67145641-50198c80-f283-11e9-84b4-c6374f6c55ab.png)

**Comment by palmerj3** [comment]
Ok I won't be able to move further on this until I can get a windows PC to test it on. Let me see if I can get one next week to use.

**Comment by andreabisello** [comment]
@palmerj3 hi,
some news?
have a nice day

**Comment by palmerj3** [comment]
Sorry for the delays on this. I do now finally have a windows PC at home where I can test this. So I expect to have more attempts to reproduce this issue very soon.

**Comment by omit66** [comment]
Just for anyone who is still facing a similar problem...
I had to add a package.json file to the root dir.

**Comment by mastrzyz** [comment]
@omit66  @palmerj3  I also hit this bug but I have a solution -> https://github.com/jest-community/jest-junit/pull/215/files care to take a look?
