### ISSUE TITLE
Why is uniqueOutputName not a boolean value?

### ISSUE THREAD

**Issue by luchsamapparat** [jest-community/jest-junit#110]
Hi,

I was wondering, why is `uniqueOutputName` not a boolean option? Currently, it requires the string value `'true'`. When setting it to boolean `true`, it does not work.

https://github.com/jest-community/jest-junit/blob/master/index.js#L28

Is this by design or a mistake?

**Comment by SimenB** [comment]
It's probably to work when passed as and environment variable. Seems like a bug though. @palmerj3?

**Comment by palmerj3** [comment]
"Boolean" values in jest-junit are handled this way so we can share the same setting key between environment variables, package.json config, reporter config, and CLI args.

Not a bug but also not the prettiest thing, I agree.

Feel free to submit a PR if you can think of a nicer way of handling this!
