### ISSUE TITLE
Stack trace in reporter isn't a relative path

### ISSUE THREAD

**Issue by JoelBrenstrum** [jest-community/jest-junit#114]
Jest CLI output:
`at Object.<anonymous> (src/client/reducers/pages/xxx.test.js:1324:26`

Jest-Junit output:
Local:
`at Object.&lt;anonymous&gt; (/Users/joelbrenstrum/Development/Projects/xxx/xxx/src/client/reducers/pages/xxx.test.js:1324:26)`
Azure Dev Ops:
`Object.<anonymous> (/home/vsts/work/1/s/xxx/src/client/reducers/pages/xxx.test.js:1060:72)`

Is it possible to get the relative path put into the stack trace?
We use Azure dev ops and these links generate as clickable but dont lead anywhere.

**Comment by palmerj3** [comment]
Hey @JoelBrenstrum! Thanks for submitting an issue.

This functionality is not built into jest-junit at the moment. The stack traces are simply taken from jest and written to a file.

But if this is something you need I would suggest you submit a PR adding a new option to jest-junit.

**Comment by JoelBrenstrum** [comment]
Hey @palmerj3 thanks for the quick reply.

I can have a look at doing that. Anything specifics you would like for the implementation? 
I was thinking we could use the rootDir config variable and normalize the path back to that.

**Comment by SimenB** [comment]
Jest's implementation lives in https://github.com/facebook/jest/blob/master/packages/jest-message-util/src/index.ts if you want some inspiration
