### ISSUE TITLE
Is there a way to generate one file per each test? 

### ISSUE THREAD

**Issue by alsvader** [jest-community/jest-junit#117]
I want to know if there is a way to generate a xml file per each test. For example if I have the following files: 
1.- MenuAppBar.test.js
2.- Alerts.test.js 
I would like to get 2 xml files and not only one named junit.xml.

**Comment by palmerj3** [comment]
Hello!

jest-junit currently does not have an option to generate a separate file per test.

But the way you could do it is by setting up separate jest projects per collection of tests and then use the jest-junit reporter configuration to set a different output path per project.

Or you could write a bash script to invoke jest multiple times and set the jest-junit output path to something different per invocation.

What is the use-case for this?

**Comment by william-wallace-simplisafe** [comment]
I have multiple tests that run in parallel and I would like each test file to produce it's own junit.xml results file to be uploaded to zephyrScale.  The current solution creates one junit file for all test files which removes any delineation between tests
