### ISSUE TITLE
XML Format

### ISSUE THREAD

**Issue by csganesh** [jest-community/jest-junit#118]
I would like to generate the unit test data in following XML format 
<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
<file path="src/plugins/device-management/__test__/devicedetails.test.js">
<testCase name="Feature when called with proper params then does somthing" duration="5"/>
<testCase name="Feature when called with wrong paramg then does nothing" duration="1"/>
</file>
</testExecutions>

Is there any options for generating the above format ?

I am using "jest-junit": "^10.0.0" version.

**Comment by palmerj3** [comment]
Hi @csganesh I think you're missing some information here. I'm unable to see the format you're referring to.

But jest-junit generates junit files according to [this xsd](https://github.com/jest-community/jest-junit/blob/master/__tests__/lib/junit.xsd) (Jenkins).

**Comment by csganesh** [comment]
Today I am generating xml report in following format but my sonar is not accepting the format jest generated.

<testsuites name=“Project” tests="144" failures="1" time="12.617">
  <testsuite name="src/common/js/__test__/servicehelpers.test.js" errors="0" failures="0" skipped="0" timestamp="2019-12-12T00:32:21" time="1.728" tests="2">
    <testcase classname="&lt;Alert /&gt; should render correctly" name="&lt;Alert /&gt; should render correctly" time="0.072" file="src/common/js/__test__/servicehelpers.test.js">
    </testcase>
    <testcase classname="&lt;Alert /&gt; Test event firing" name="&lt;Alert /&gt; Test event firing" time="0.119" file="src/common/js/__test__/servicehelpers.test.js">
    </testcase>
  </testsuite>
<testsuites>

Sonar expecting format is

<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
<file path="src/plugins/device-management/__test__/devicedetails.test.js">
<testCase name="Feature when called with proper params then does somthing" duration="5"/>
<testCase name="Feature when called with wrong paramg then does nothing" duration="1"/>
</file>
</testExecutions>


I don't know if I am missing any configuration.
Attaching sonar expected format
https://docs.sonarqube.org/latest/analysis/generic-test/

Thanks for your quick response.  Your help highly appriciated

**Comment by palmerj3** [comment]
jest-junit isn't designed to generate generic-test format. However sonarqube does support junit so if you choose to stick with jest-junit you should be able to use the files it generates.

See https://docs.sonarqube.org/pages/viewpage.action?pageId=1442166
