### ISSUE TITLE
Nested describes - separate test suites

### ISSUE THREAD

**Issue by dastewa** [jest-community/jest-junit#130]
I was experimenting with this package and found that when there are multiple sibling describes in a test file, only the first one appears in the report as it's own test suite. Is there a setting I might be missing to ensure that sibling describes appear as their own test suites? The use of only the first describe if there are multiple siblings seems arbitrary unless I missed in the docs - definitely possible :).

Related to this, tests from sibling describes are reported as children of the first describe block, which seems to create a disconnect between the test report and the actual test structure, in my opinion at least.

If there aren't settings for controlling these, can you give me a hint for what files I should start taking a look at for implement these changes? 

Thanks!

**Comment by palmerj3** [comment]
Hello!

When I tested nested describe blocks locally this is what I see.

foo.test.js
```
describe('foo', () => {
  describe('bar', () => {
    it ('should do something', () => {
      expect(true).toBe(true);
    });
  });
});
```

junit.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="1" failures="0" time="0.834">
  <testsuite name="foo" errors="0" failures="0" skipped="0" timestamp="2020-06-21T15:55:12" time="0.401" tests="1">
    <testcase classname="foo bar should do something" name="foo bar should do something" time="0.001">
    </testcase>
  </testsuite>
</testsuites>
```

As you can see it combines the name of nested describe blocks in the testsuite.

Is this what you are referring to? From the way you describe the issue it sounded like certain describe blocks were ignored but I'm not seeing that.

**Comment by dastewa** [comment]
Thanks for the quick reply! And yep, I'm definitely seen the exact behavior you showed for nested describe blocks - so that's definitely my bad for not explaining my thoughts well! I was moreso looking at the behavior with adjacent describe blocks. For example:

```
describe('foo', () => {
  it('foo test', async () => {
    return;
  });
});

describe('bar', () => {
  it('bar test', async () => {
    return;
  })
})
```
Gives this report:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Test Suite" tests="2" failures="0" time="16.521">
  <testsuite name="foo" errors="0" failures="0" skipped="0" timestamp="2020-06-21T16:01:11" time="16.045" tests="2">
    <testcase classname="foo foo test" name="foo foo test" time="0.001">
    </testcase>
    <testcase classname="bar bar test" name="bar bar test" time="0">
    </testcase>
  </testsuite>
</testsuites>
```
I see that the classname for `bar test` has its parent's describe block name. But I'm wondering if it was possible to have each adjacent describe block represented as it's own test suite. The report would be like this instead:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Test Suite" tests="2" failures="0" time="16.521">
  <testsuite name="foo" errors="0" failures="0" skipped="0" timestamp="2020-06-21T16:01:11" time="16.045" tests="2">
    <testcase classname="foo foo test" name="foo foo test" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="bar" errors="0" failures="0" skipped="0" timestamp="2020-06-21T16:01:11" time="16.045" tests="2">
    <testcase classname="bar bar test" name="bar bar test" time="0">
    </testcase>
  </testsuite>
</testsuites>
```
Feel free to let me know if this is a bad idea! I was just thinking that the latter report would better represent the structure of the tests in this case. What do you think?

**Comment by palmerj3** [comment]
Ahh ok I see now. Let me do some testing here on my end and see if anything can be done.

I do believe that jest treats each unique file (e.g. foo.test.js) as a test suite not each describe block. But let me confirm that.

**Comment by palmerj3** [comment]
Ok so jest actually doesn't seem SUPER opinionated on this so I was wrong to say that.

It's certainly easier to have things configured the way I do. But glancing at what jest sends to reporters like jest-junit you could, with some work, configure the output so each describe block is a unique test suite in junit.xml.

The hard part would be how to treat a combination of nested and adjacent describe blocks.

When I have the following foo.test.js file with two adjacent describe blocks:
```
describe('foo', () => {
  it ('should do something', () => {
    expect(true).toBe(true);
  });
});

describe('foo2', () => {
  it ('should do something2', () => {
    expect(true).toBe(true);
  });
});
```

This is what jest sends the jest-junit reporter (or any other reporter).
https://gist.github.com/palmerj3/26dc35e47ed20d5d332db1458cde566d

So you could theoretically make a PR that would allow for this functionality. But it might be such a significant change that it would warrant a fork.

**Comment by palmerj3** [comment]
As you can see from the:
  `"numTotalTestSuites": 1,`

In the output - jest does treat each unique test file as a suite, not each unique describe block.
But with some work you could fork jest-junit and have the output be represented the way you'd like.

**Comment by dastewa** [comment]
Thank you so much for taking the time to look into this, I really appreciate it! The info you shared showing what jest is sending to the reporters was key. I incorrectly thought that jest considered each describe block as a suite so this is great to know.

I think I'll still take a stab at forking and trying the implementation for my own learning because this project is super useful. Huge thanks again for pointing me in the right direction, I'll go ahead and close this issue. Cheers!

**Comment by palmerj3** [comment]
No worries!

If you end up with something that works I would love to see it so please share.

**Comment by btadros** [comment]
I experience unfortunately the same issue. Why was this issue closed, if not solved?

**Comment by palmerj3** [comment]
Read the thread and you'll see pretty clearly
