### ISSUE TITLE
Invalid Character 0x1b Not Stripped

### ISSUE THREAD

**Issue by fabb** [jest-community/jest-junit#134]
Somehow @testing-library sometimes generates `0x1b` characters in the test output. These are currently not stripped by jest-junit, and they result in an invalid XML file.

Example:
![Screenshot 2020-06-28 at 08 16 12](https://user-images.githubusercontent.com/153960/85939782-7e726000-b918-11ea-90b3-bc1420220042.png)

[jest-test-results.xml.txt](https://github.com/jest-community/jest-junit/files/4841766/jest-test-results.xml.txt)

It seems like @testing-library uses `0x1b` when it truncates the debug output of the DOM when it's too long.

**Comment by abeggchr** [comment]
Same issue here.

**Comment by palmerj3** [comment]
Please create a repository that reproduces this issue and then I can take a look.

Thanks

**Comment by fabb** [comment]
I created a repo here: https://github.com/fabb/jest-junit-0x1b-bug

I didn't see the `0x1b` anymore though at the cutoff point. Maybe this was changed in @testing-library.

Now the question is whether I just could not reproduce it or if it really was changed in @testing-library 😄.
And whether jest-junit should just strip some special character ranges for safety.

**Comment by fabb** [comment]
@abeggchr can you still reproduce with the lasest jest and testing-library versions?

**Comment by palmerj3** [comment]
@fabb ok at this point nothing is actionable from my side.

Looking at your original junit file you linked in the issue description I don't see any 0x1b characters.. 

So the screenshot that shows it - is that what appears in the console output?

jest-junit only writes junit.xml files and doesn't contribute to what you see in the console output. That would be the jest default reporter or another reporter if you're using one.

And for clarity - jest-junit already strips ansi characters from the output of the failure tag. See here.
https://github.com/jest-community/jest-junit/blob/master/utils/buildJsonResults.js#L193

Closing this issue for now but if you're able to reproduce something where characters are showing up in junit.xml files and you have a repo that reproduces the issue I'll re-open.

**Comment by fabb** [comment]
> Looking at your original junit file you linked in the issue description I don't see any 0x1b characters..

0x1b is a non-printable character, it is `Escape`.
Editors and the console do not show this character by default, the screenshot is from Sublime with some option activated so it shows such non-printable characters.

> So the screenshot that shows it - is that what appears in the console output?

No it's not the console output, it's the file output captured with `JEST_JUNIT_OUTPUT_NAME='.jest-test-results.xml' react-scripts test --ci --env=jsdom --reporters=jest-junit  `.

> And for clarity - jest-junit already strips ansi characters from the output of the failure tag. See here.

Ok but I think 0x1b **is** an ANSI character, it's just non-printable.

> Closing this issue for now but if you're able to reproduce something where characters are showing up in junit.xml files and you have a repo that reproduces the issue I'll re-open.

> Closing this issue for now but if you're able to reproduce something where characters are showing up in junit.xml files and you have a repo that reproduces the issue I'll re-open.

Makes sense! Let's hope it has been fixed in testing-library or jest. But as said, maybe it makes sense to strip non-printable ANSI characters too.

**Comment by fabb** [comment]
Ah now I get it, `strip-ansi` removes ansi escape codes.

Maybe the issue in my problematic case was that the output was cutting off **in the middle** of the escape code, therefore not being stripped by the ansi escape code. In the screenshot above you can see `0x1b[ ...` which looks like the first part of a cut off ansi code. strip-ansi just removes **full** ansi escape codes:

https://github.com/chalk/ansi-regex/blob/master/index.js#L5

In this case I think testing-library and/or jest should already produce a correct output that only contains non-cut-off ansi codes. As said, maybe it‘s already fixed on their side since I could not reproduce it in the example repo.
