### ISSUE TITLE
Add jUnit properties per testcase

### ISSUE THREAD

**Issue by BrunnerLivio** [jest-community/jest-junit#135]
## Description

JUnit allows us to add properties for each test cases as well. At the moment jest-junit only supports properties per test suite.

The XML should look like this (example with PyTest):

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="12.151">
  <testcase classname="validation_tests" file="validation_tests.py" line="14" name="test" time="0.07963943481445312">
    <properties>
      <property name="review_date" value="Mon, 06 Aug 2018 12:56:33 +0200"/>
      <property name="requirements" value="000, 001"/>
      <property name="author" value="snowj1"/>
      <property name="id" value="dbcf79da"/>
      <property name="reviewer" value="hodor"/>
      <property name="start_time" value="Thu, 31 Jan 2019 09:33:52 +0100"/>
      <property name="description" value="Tests the mirror creation on molior"/>
      <property name="end_time" value="Thu, 31 Jan 2019 09:33:52 +0100"/>
    </properties>
    <system-out>
      ...
    </system-out>
  </testcase>
  <testcase ...>
    [...]
  </testcase>
</testsuite>
```

With PyTest this can be done like this:

```python
@pytest.mark.metadata(
    id="dbcf79da",
    author="snowj1",
    requirements=["000", "001"],
    reviewer="hodor",
    review_date="Fri, 05 Oct 2018 13:59:25 +0200",
)
`def test_run():`
```

## Solutions I have thought of

Since I am not quite sure whether it is possible to extend the Jest `it`/`test`-function to pass metadata, we may need to work around this.

Let's assume I have the following test:

```js
it('[000] should test whether true is true', () => {
    expect(true).toEqual(true)
});
```

for me, it would be sufficient if I can just compute the properties myself in `junitProperties.js`

```js
// for test suites
function testSuite() {
  return {
     key: "value"
  }
}

function testCase(execution) {
  const id = execution.title.split('[')[1].split(']')[0];

  return {
    id
  };
}

module.exports = { testSuite, testCase }
```

which would result in:

```xml
<testsuites name="jest tests">
  <testsuite name="addition" tests="1" errors="0" failures="0" skipped="0" timestamp="2017-07-13T09:42:28" time="0.161">
    <properties>
        <property name="key" value="value" />
    </properties>
    <testcase classname="[000] should test whether true is true'" name="should test whether true is true'" time="0.004">
        <properties>
      <property name="id" value="000"/>
    </properties>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by BrunnerLivio** [comment]
I was able to create a "hacky" - but nicer - workaround if the proposed solution above would get accepted.

My test file looks like this:

```js
const mit = require("./metadata");

mit("should check whether true equals true", { id: "000", "reviewer": "OnePunchMan" }, () => {
  expect(true).toEqual(true);
});
```
 
The `metadata.js`:

```js
const { existsSync, readFileSync, writeFileSync } = require("fs");

function mit(name, metadata, func) {
  // Store the metadatas
  let metadataStorage;

  if (existsSync("metadata.json")) {
    metadataStorage = JSON.parse(readFileSync("metadata.json"));
  } else {
    metadataStorage = {};
  }

  metadataStorage[name] = metadata;

  writeFileSync("metadata.json", JSON.stringify(metadataStorage));

  // Execute the test
  it(name, func);
}

module.exports = mit;
```

Then I can read the metadatas and associate it with a test title in `junitProperties.js`:

```js
module.exports = (testExecution) => {
  const metadatas = require("./metadata.json");
  console.log(metadatas);
  return metadatas[testExecution.title];
};
```

The log outputs:

```
...
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.074 s
Ran all test suites.
{ 'should check whether true equals true': { id: '000', reviewer: 'OnePunchMan' } }
```

**Comment by palmerj3** [comment]
Hello!

I would really love to have per test case properties. It's something that I wished junit supported.

But ultimately there isn't a junit xsd standard that I'm aware of which actually supports this. So if PyTest supports this then they are most likely generating invalid junit files.

I have to be very careful and conservative about what gets added to jest-junit because it's used in such a wide variety of CI platforms. Junit has several different standards and I've chosen to validate jest-junit against jenkins junit xsd.

But like I said I'm not aware of any junit xsd's that support test case properites.

**Comment by BrunnerLivio** [comment]
@palmerj3 Understandable.

I just dug deeper and seems like `@pytest.mark.metadata` is a custom decorator in the codebase I snooped in.
In the end, this decorator calls PyTests [`record_property`](https://docs.pytest.org/en/stable/reference.html#_pytest.junitxml.record_property) function:

> **[record_property]** Add an extra properties the calling test. User properties become part of the test report and are available to the configured reporters, like JUnit XML. The fixture is callable with (name, value), with value being automatically xml-encoded.

Nonetheless, since this is not a standard may I'll need to look into creating an additional plugin. Thanks for you help @palmerj3

**Comment by mhmiles** [comment]
This issue is marked as completed but I see no associated code change or documentation showing that this feature is available. This [external issue](https://github.com/allure-framework/allure2/pull/1833) seems to refer to this issue as if the feature is complete. Would it be possible to get some clarification?
