### ISSUE TITLE
Junit xml not printing the console log

### ISSUE THREAD

**Issue by Ppkd2021** [jest-community/jest-junit#145]
Hi,

I did set up the property includeConsoleOutput: 'true' under jest.config.ts but while executing the test cases the console logs are getting printed on console as mentioned below but they are not coming under junit.xml and I do have 5 test files under the folder.
console.log
      Yes
 at Object.<anonymous> (playwright/e2e/user-onboarding-journey/logtest.test.ts:11:17).
I am using jest-junit": "10.0.0".
Can you let me know how can I fix this issue as I see the same issue reported earlier and fixed was merged?
https://github.com/facebook/jest/pull/8739
I tried to debug using buildJsonResult.Js, In that, it is throwing undefined for suite.console. Please let me know if there is a fix for that.

**Comment by palmerj3** [comment]
See https://github.com/jest-community/jest-junit/pull/96#issuecomment-700168772 for more info
