### ISSUE TITLE
Can we exclude skipped tests from results?

### ISSUE THREAD

**Issue by creage** [jest-community/jest-junit#148]
I'm running a `jest` with `--testNamePattern` parameter, which filters out tests that do not satisfy the pattern.

The issue that the final `.xml` file lists ALL of tests, marking those that were not run by `<skipped/>` element. This results into too much noise when viewing such output.

Can we somehow exclude skipped tests from results?

**Comment by palmerj3** [comment]
Hello!

They are skipped. So I think that makes perfect sense to report it as such.

I'm not entirely convinced we should have an option to remove them from the list because junit.xml is supposed to represent which tests ran, which were skipped, etc.

**Comment by creage** [comment]
Let me explain the case:

We have an app with thousands of tests, and they are tagged by areas - `security`, `integration`, `network` etc.

Now, when we run tests by `security` tag, we get a result of like 200 `passed`, 3000 `skipped` tests. Same goes with every other area - we get these **~3000** `skipped` entries next to our real test run results. Normally we are not interested in skipped entries - we want to see greens and reds.

Having an option to not include `skipped` tests in results would definitely improve results readability, and overall report quality. It's kind of different types of logging - verbose vs info.

**Comment by palmerj3** [comment]
I think for this use-case what I would suggest doing is having a post-test npm script which truncates the junit.xml file the way you would like before CI picks up on the results

**Comment by creage** [comment]
@palmerj3 you are right - it is an option. But this would require another XML parsing, looping, removing, saving XML back. I mean, it is not impossible, but it is kinda double work, comparing to just NOT writing unwanted nodes in the first place.

I agree that the duty of reporter is to report whatever results are, but having a bit more granular control over the process might give some value too.

**Comment by palmerj3** [comment]
I do agree with you. Processing a large file could possibly add a few seconds to build times.

But if I do this then it would open up a lot of additional requests for more granular control of the output. Don't show passed tests only failed ones, only show things that match this regex or that passes this function.

Since junit is supposed to represent exactly what the test runner did I think my position here is reasonable.

**Comment by creage** [comment]
what if you make the control of the behavior inversed? Like, accept a filtering function that will decide if a particular test result should be included into the output or not, letting users control that?

Should add relatively small overhead to the implementation, and give more controls to users.

**Comment by palmerj3** [comment]
I would much rather not add additional bloat to the library if it's not needed and given that post-processing can easily handle this use-case that is what I would rather teams try.

But if that doesn't work well or if a few others ask for this functionality I would be open to it, of course.

What is your thinking when it comes to that approach?
If you try post-processing the xml file and it's problematic then I would be open to adding the functionality to the library.

**Comment by creage** [comment]
It is not problematic, but still...

Here is what I have for Windows setup:

```powershell
Get-ChildItem results\*.xml | % {

	[Xml]$xml = Get-Content $_.FullName

	$xml.SelectNodes("//testsuite[not(@skipped=0)]") | % {$_.ParentNode.removechild($_) } | Out-Null

	$xml.OuterXml | Out-File $_.FullName
}
```

This requires additional stack to know and is not cross-platform. But it solves my problem at least.
