### ISSUE TITLE
includeShortConsoleOutput not adding message in failure testcase

### ISSUE THREAD

**Issue by pushkarajawad** [jest-community/jest-junit#150]
We are using jest-junit   "jest-junit@10.0.0" for reporting. to include message in failure we have added includeShortConsoleOutput in config file but it still not showing message tag in the report.
includeConsoleOutput is working file, it is adding entire stack trace in the report, but we want short error message.

Config: 
"jest-junit", {
        "suiteName": "OmniChannel e2e tests",
        "outputDirectory": "./reports/",
        "outputName": "./junit.xml",
        "usePathForSuiteName": "true",
        "includeShortConsoleOutput": "true",
        "includeConsoleOutput": "true",
      }

<testcase classname="abc" name="abcd" time="0.001">
      <failure>TimeoutError: Timeout 30000ms exceeded during page.waitForSelector.
================ page.waitForSelector logs ================
[api] waiting for selector &quot;button[data-id=&apos;dynamics-button&apos;]&quot; to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at ProgressController.run (testpath\node_modules\playwright\lib\progress.js:73:30)
    at Object.runAbortableTask (testpath\node_modules\playwright\lib\progress.js:29:23)
    at Page._runAbortableTask (testpath\node_modules\playwright\lib\page.js:86:27)
    at Frame.waitForSelector (testpath\node_modules\playwright\lib\frames.js:384:27)
    at Frame.waitForSelector (testpath\node_modules\playwright\lib\helper.js:79:31)
    at _attributeToPage (testpath\node_modules\playwright\lib\page.js:131:61)
    at Page._attributeToPage (testpath\node_modules\playwright\lib\page.js:356:20)
    at Page.waitForSelector (testpath\node_modules\playwright\lib\page.js:131:21)
    at Page.waitForSelector (testpath\node_modules\playwright\lib\helper.js:79:31)
    at AdminPage.&lt;anonymous&gt; (testpath\e2e\areas\core\pages\BasePage.ts:103:44)
  -- ASYNC --

**Comment by palmerj3** [comment]
Hi please create a github repository that recreates this issue and I'll be happy to take a look

**Comment by PushkarajAwad2** [comment]
Hi you can check this repo
https://github.com/PushkarajAwad2/jest-playwright-junit-demo.git

**Comment by PushkarajAwad2** [comment]
@palmerj3 any updates on it.

**Comment by palmerj3** [comment]
Not my full time job so I'll take a look when I can tomorrow

**Comment by PushkarajAwad2** [comment]
Hi @palmerj3 Could you please help me on this issue?

**Comment by palmerj3** [comment]
So I looked into this. shortConsoleOutput does not look at the failure tags or error messages. It ONLY looks at console output (stdout).

So the issue you're raising here should be a feature request.

Please write another issue as a feature request and feel free to submit a pull request.

**Comment by PushkarajAwad2** [comment]
Hi @palmerj3 thank you for looking into this issue.
Our end goal is to display error message while publishing junit report in azure devops(VSTS).
e.g.

![image](https://user-images.githubusercontent.com/68724672/96644681-3c619580-12de-11eb-8423-66262839104d.png)
Currently report is only adding stack trace not the error message. 
So to add this message, can you please let us know what to do. 
As per my understanding if we have errormesage attribute in <failure> then it will show display the error message in report.
but currently after execution I am not able to see the error message tag,

    <failure>page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector &quot;button[data-id=&apos;dynamics-button&apos;]&quot; to be visible

**Comment by palmerj3** [comment]
So I think this is likely the case of azure devops interpreting junit files incorrectly. The difference between a test failure and a test error is that an error is when a test cannot be executed. Whereas a failure is when a test runs but fails while the test is running.

You can test this behavior by using the latest version of jest-junit (v12.0.0), setting the option reportTestSuiteErrors, and creating a test file with a syntax error in it.

At that point a junit file containing an error xml tag will be generated.

But as mentioned that tag is not intended to be filled out for tests that run and fail (like yours above).
