### ISSUE TITLE
Replacement of <rootDir> happens too late

### ISSUE THREAD

**Issue by arabull** [jest-community/jest-junit#153]
The final output location is determined using the following logic:

```
  const outputName = (options.uniqueOutputName === 'true') ? getOptions.getUniqueOutputName() : options.outputName
  const output = path.join(options.outputDirectory, outputName);
  const finalOutput = getOptions.replaceRootDirInOutput(jestRootDir, output);
```

Unfortunately, the call to `path.join()` scrubs `<rootDir>` from the outputDirectory, so any path that uses that syntax ends up incorrect.

Tweaking the order to replace `<rootDir>` first solves the problem:

```
  const outputName = (options.uniqueOutputName === 'true') ? getOptions.getUniqueOutputName() : options.outputName
  const output = getOptions.replaceRootDirInOutput(jestRootDir, options.outputDirectory);
  const finalOutput = path.join(output, outputName);
```

**Comment by palmerj3** [comment]
Nice catch!

Could you submit a PR to fix this and include a test case that makes sure rootDir isn't stripped out?

**Comment by arabull** [comment]
Yep, working on it now. Will hopefully have something later today.

**Comment by arabull** [comment]
There is more nuance here than what I originally reported. The problem is actually when the outputDirectory looks like `<rootDir>/../some/dir`. In that case, `path.join()` assumes the `..` cancels out the `<rootDir>`, which seems entirely reasonable. Unfortunately, it means the final value is `some/dir`, and that ends up rooted at `process.cwd()`, which doesn't always match `<rootDir>`.

In our case, our Jest root directory isn't at the root of the project, but we want the final report to end up in the root. That's why we're using that pattern.

The fix suggested above works and is the correct fix, but I wanted to provide a little more detail for what's going on. It was a bit unfair to blame `path.join()`. It's just doing what it thinks is right.

**Comment by taitruong** [comment]
I just found this bug after spending too much time why `outputDirectory: "<rootDir>/../../packages"` is not working :(. The workaround is not using rootDir: `outputDirectory: "../../packages"`.
