### ISSUE TITLE
Is it possible to have custom attributes ?

### ISSUE THREAD

**Issue by mohanraj-r** [jest-community/jest-junit#163]
1. Would like to add custom attributes to test case node that are populated at runtime (and made use of by downstream processes in CI). Would that be possible?

2. Like that certain Template names can be dynamic functions.. Are there any docs/examples/tests on what attributes are present in the callback `vars` obj passed to the template functions e.g. [jest-junit#example-5](https://github.com/jest-community/jest-junit#example-5)?

**Comment by palmerj3** [comment]
Hey!

That's not possible with jest-junit since we only will generate xml that is compatible with most junit xsd specs.

If you need custom attributes you'd have to fork jest-junit or write some utility that processes the generated xml file.

**Comment by mohanraj-r** [comment]
Thanks for the quick response @palmerj3 

How about 
> Are there any docs/examples/tests on what attributes are present in the callback vars obj passed to the template functions e.g. jest-junit#example-5?
