### ISSUE TITLE
Question: Junit.xml report generated from jest-junit, supports <error> tag in the report?

### ISSUE THREAD

**Issue by Manish123chandel** [jest-community/jest-junit#166]
Hi @palmerj3 @orta @marcinczenko ,

I trying to generate the Junit .xml with the help of jest-junit library.
the report generated from this library is some unexpected behavior.

May I know the report generated from this lib supports <error> tag?

cos I am trying to generate everytime it create <failure> tag in report as show as below?

how to segragate errors and failure in this report?

Could you please help me on this?

![image](https://user-images.githubusercontent.com/21332491/118924143-3ebcc880-b96f-11eb-8875-45bcdd66ff55.png)

**Comment by palmerj3** [comment]
I'm not sure what you mean by "supports tag" or "everytime it create tag". Can you give me an example?

For differentiating errors and regular failures you need to enable the "reportTestSuiteErrors" which you'll find listed in the README documentation.
