### ISSUE TITLE
Bazel + Jest: Dynamic location for jest-junit's xml file

### ISSUE THREAD

**Issue by daivinhtran** [jest-community/jest-junit#167]
As mentioned in https://github.com/jest-community/jest-junit/pull/34#issuecomment-350125309, when we run jest with Bazel, the tests are run in a test sandbox and the directory to the sandbox is not deterministic until the execution phase.

When bazel runs jest, bazel writes `test.xml` differently from `jest-junit`. `test.xml` (generated by bazel) is in written in 
`/private/var/tmp/[computer_name]/[unconsistent_hash]/execroot/[workspace_name]/bazel-out/darwin-fastbuild/testlogs/package_name/jest/test.log` while `jest-junit` writes to a folder defined by the config or `JEST_JUNIT_OUTPUT_DIR` env var.

The path to the testlogs (e.g. [`XML_OUTPUT_FILE`](https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions)) isn't defined until jest is executed by bazel. So we don't know the value to pass in `JEST_JUNIT_OUTPUT_DIR` or the config statically.

It would be great if we can pass in a global variable name for `jest-junit` to look at runtime. Something like
```
"jest-junit": {
  "outputName": "env_var:JEST_JUNIT_OUTPUT_DIR"
}
```

I'm happy to put up a PR for the proposed feature if you think it's a good idea.

**Comment by palmerj3** [comment]
Hey! Thanks for raising this issue.

I'd be happy to accept a PR contribution that adds this functionality.

Just curious wouldn't you be able to make use of jest-junit's environment variable to make this work?

`JEST_JUNIT_OUTPUT_DIR="$XML_OUTPUT_FILE" jest`

**Comment by daivinhtran** [comment]
Thanks @palmerj3 for the quick response.

I've digged further and found out bazelbuild's rules_nodejs recently add the `env` attribute to do what you just described above.
PR: https://github.com/bazelbuild/rules_nodejs/pull/2499
Issue: https://github.com/bazelbuild/rules_nodejs/issues/2497

However, we still need another config like `JEST_JUNIT_OUTPUT_FILE` instead of `JEST_JUNIT_OUTPUT_DIR` or `JEST_JUNIT_OUTPUT_NAME` because `XML_OUTPUT_FILE` (set by bazel) is the full path the xml file instead of just directory.

Wwe need the full path (dir + filename) to be dynamic is that bazel has the capability to [retry on flaky tests](https://docs.bazel.build/versions/master/command-line-reference.html#flag--flaky_test_attempts) and we need to store and process all the xmls (both failed and passed attempts) to get better reporting on flaky tests.

**Comment by daivinhtran** [comment]
Hi @palmerj3 . Please take a look whenever you have a chance. https://github.com/jest-community/jest-junit/pull/168. Thank you.

**Comment by palmerj3** [comment]
Thank you!

I just published https://github.com/jest-community/jest-junit/releases/tag/v12.1.0 with your changes included.
