### ISSUE TITLE
Generates unnecessary junit.xml in the tests root (jest 26 and jest-junit 12.2.0)

### ISSUE THREAD

**Issue by hermanzamula** [jest-community/jest-junit#173]
Hi, I need `junit.xml` file to be in the reports directory `../../reports/shared`. I'm overriding `outputDirectory` for that:

```
  reporters: ['default', ['jest-junit', { outputDirectory: '../../reports/shared', suiteName: 'shared tests' }]],
```
But along with the `junit.xml` in `../../reports/shared` it generates extra `junit.xml` in the folder where `jest.config.js` is defined:
![image](https://user-images.githubusercontent.com/2499975/122535020-ce679c80-d02b-11eb-84df-5dafe7d96f0b.png)

I've tried different options but unable to get rid of this `junit.xml` file.
Also it contains not overriden suiteName (file in `../../reports/shared/junit.xml` has `name="shared tests"`):

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="174" failures="0" errors="0" time="2.525">
  <testsuite name="SharedCommonUtility" errors="0" failures="0" skipped="0" timestamp="2021-06-18T08:53:09" time="0.856" tests="53">
```

My `jest.config.js`:

```
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverage: true,
  reporters: ['default', ['jest-junit', { outputDirectory: '../../reports/shared', suiteName: 'shared tests' }]],
  testResultsProcessor: 'jest-junit',
  verbose: true,
  silent: true,
  maxWorkers: 3,
  rootDir: '../../shared',
  roots: ['<rootDir>/../testing/shared-tests'],
  coverageDirectory: '../reports/shared',
};

```

**Comment by palmerj3** [comment]
Please create a repository on github that reproduces this problem and share it here.

Thank you

**Comment by MarcelRittershaus** [comment]
I had the same situation. The solution for me was to remove: testResultsProcessor: 'jest-junit'  in my config.

The following jest.config.js setting should resolve your ISSUE
`
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverage: true,
  reporters: ['default', ['jest-junit', { outputDirectory: '../../reports/shared', suiteName: 'shared tests' }]],
  verbose: true,
  silent: true,
  maxWorkers: 3,
  rootDir: '../../shared',
  roots: ['<rootDir>/../testing/shared-tests'],
  coverageDirectory: '../reports/shared',
};
`
