### ISSUE TITLE
Update strip-ansi to v6.0.1 due to security vulnerability about ansi-regex(v4.1.0)

### ISSUE THREAD

**Issue by KeYu-dev** [jest-community/jest-junit#183]
Hi, jest-junit team.

Jest-junit is a great libray. But recently our component and governence pipeline detect security vulnerability issue about ansi-regex(v4.1.0) when using jest-junit package.

> Description: ansi-regex is vulnerable to Inefficient Regular Expression Complexity
> Recommendation: Upgrade ansi-regex from 4.1.0 to 5.0.1 to fix the vulnerability

To update ansi-regex to v5.0.1, jest-junit can update strip-ansi to v6.0.1
https://github.com/chalk/strip-ansi/tree/v6.0.1

How do you think about this?

Thanks in advance.

**Comment by SimenB** [comment]
Could you send a PR for that? 🙂

**Comment by KeYu-dev** [comment]
> Could you send a PR for that? 🙂

I create a PR, can you check it out?
https://github.com/jest-community/jest-junit/pull/188

**Comment by holger-koenig** [comment]
@palmerj3 Could you create a release for this change? Thanks!
