### ISSUE TITLE
"Failure" XML element in "Testcase" is missing a "type" property

### ISSUE THREAD

**Issue by ryanarifin134** [jest-community/jest-junit#196]
Hello!

I've noticed in the XML being generated from my jest results that, in the failure case of a test case, a required property called "type" (specifying the type of assert that caused the failure) is missing.

When I say "required property", I mean something that seems generally agreed upon - after some research, there doesn't seem to be one source of truth on the JUnit XML spec. However, looking at [this](https://stackoverflow.com/questions/4922867/what-is-the-junit-xml-format-specification-that-hudson-supports) SO post, and [this](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L108) JUnit specification, I think it would be safe to say that the `type` property on the `failure` XML element should be generated.

This would be helpful for 2 reasons:

1. This is valuable information you can use when serializing/deserializing and processing the generated JUnit XML
2. This causes deserialization to fail for certain libraries that expect that `type` property to exist (my company is using Java the Jackson XML parser, and it's failing because of this).

I'd be totally willing to make this PR myself, but I just wanted to make sure the good maintainers of this awesome library agree!

**Comment by ryanarifin134** [comment]
Here's what I mean by the `failure` element missing the `type` property under a `testcase` element!

This is a sample JUnit XML generated with a failing test case.
<img width="1067" alt="Screen Shot 2022-01-05 at 12 38 05 PM" src="https://user-images.githubusercontent.com/19615186/148263380-a444353b-6044-4a58-9fb1-e124760f6267.png">

**Comment by palmerj3** [comment]
Hello! Thanks for submitting an issue!

Can I ask: what CI system do you use which has this as a required field?

As you noted there is no single standard for junit. So I have chosen to validate everything jest-junit generates against the jenkins junit xsd. If i add this field then I would have to break jenkins support.

https://github.com/jest-community/jest-junit/blob/master/__tests__/lib/junit.xsd#L42

**Comment by ryanarifin134** [comment]
We use a custom in-house CI system.

But mainly, where this is an issue is the Jackson XML parser is requiring at least one field: `message` or `type`.

If you're already following that spec, than in that case, I think I should be sending this issue to the Jackson XML team! Wouldn't make sense for you to cause back compat problems to fix a problem I'm dealing with.

Just realized this is a bug with the Jackson XML parsing library, and not yours.

My bad!
