### ISSUE TITLE
Options are not taken into account when set on jest.config.js instead of package.json

### ISSUE THREAD

**Issue by blephy** [jest-community/jest-junit#201]
Hi,

Seems jest-junit options are not taken into account if they are set in jest.config.js. 

```js
module.exports = {
  rootDir: '.',
  moduleFileExtensions: ['cjs', 'json', 'js', 'jsx', 'ts', 'tsx'],
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.+(cjs|js|ts|tsx)'],
  coveragePathIgnorePatterns: ['.nocov.ts'],
  coverageDirectory: '<rootDir>/reports/jest',
  coverageReporters: ['text', 'html', 'lcov', 'json'],
  collectCoverageFrom: ['<rootDir>/src/**/*', '!**/node_modules/**'],
  coverageThreshold: {
    global: {
      statements: 100,
    },
  },
  reporters: [
    'default',
    [
      'jest-junit',
      {
        suiteName: 'jest tests',
        outputName: 'jest-junit.xml',
        outputDirectory: '<rootDir>/reports/junit',
        ancestorSeparator: ' › ',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
        uniqueOutputName: 'false',
        usePathForSuiteName: 'true',
      },
    ],
  ],
  testResultsProcessor: 'jest-junit',
  testPathIgnorePatterns: [],
```

when running jest with this configuration : 
- outputName is `junit.xml` instead of `jest-junit.xml`
- outputDir is `<rootDir>` instead of `<rootDir>/reports/junit`
- any other option are not used too ...

When specifying this option in package.json, everything is working.

Did i missed something ?

**Comment by palmerj3** [comment]
Hey thanks for submitting an issue!

I believe the issue here is that you've specified jest-junit both as a reporter and a testResultsProcessor.
Remove testResultsProcessor and let me know if the configs work.

testResultsProcessor's don't pay attention to reporter configs.

**Comment by blephy** [comment]
Hey @palmerj3 

You right, this is working :)

Can we update the documentation ?

**Comment by palmerj3** [comment]
I feel the docs do a pretty good job showing intended usage of reporter vs testResultsProcessor but feel free to submit a PR clarifying the language and I'll be happy to merge.

**Comment by blephy** [comment]
You right, this is pretty clear. I maybe read the docs from `npm` or a long time ago :)
