### ISSUE TITLE
Add "fileTemplate" to complement "addFileAttribute"

### ISSUE THREAD

**Issue by ceefour** [jest-community/jest-junit#202]
In a monorepo, the package is not at the root of git repository. 

Meaning, `addFileAttribute` becomes inaccurate.

Please add `fileTemplate` so that we can use like:

```
fileTemplate: 'packages/qc-api/{filepath}',
```

which will be correct path relative to repository root.

**Comment by ceefour** [comment]
The issue is project root != repository root.

In my case:

* repository root: `/`
* project root: `/package/qc-api`

**Comment by palmerj3** [comment]
I see now I understand. Thanks for taking the time to explain!

Right now I think I can safely say we don't have anything built in to jest-junit to easily help with this situation.

Feel free to submit a PR adding this functionality and I will review it. Or you could also have a posttest npm script that decorates the junit.xml file that jest-junit creates and prepends the rest of the path.

**Comment by marvinroger** [comment]
I have the exact same use case, here's a PR: https://github.com/jest-community/jest-junit/pull/209

**Comment by ceefour** [comment]
Super thank you @marvinroger 😎

**Comment by jjoselv** [comment]
Maybe we can expand this with https://github.com/jest-community/jest-junit/issues/256, so we have a way to resolve to the package dir.
