### ISSUE TITLE
not able to produce junit file by adding JEST_JUNIT_OUTPUT_NAME="junit.xml" before jest command

### ISSUE THREAD

**Issue by PavanMudigondaTR** [jest-community/jest-junit#213]
not able to produce junit file by adding JEST_JUNIT_OUTPUT_NAME="junit.xml" before jest command. Could you please help. I see your team made a release recently and i tried to follow your latest instruction but still not able to produce junit xml from command line. For CI/CD we need to add command line arg to produce junit file rather than asking all teams to add in their package.json file.

**Comment by PavanMudigondaTR** [comment]
It appearing we are not able to produce junit xml even with arugument added in pacakge.json file. please help!

**Comment by palmerj3** [comment]
I will need a lot more information in order to help you. Could you please put together a repository that reproduces this issue?

Once you do that I'd be happy to take a look.

**Comment by PavanMudigondaTR** [comment]
My apologies. We were doing something wrong but later we figured and were able to generate junit file. Thanks for responding back !

**Comment by t-shreysingh** [comment]
Not able to produce junit.xml file using command
JEST_JUNIT_OUTPUT_NAME="file.xml" jest   
Error: 'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command,
operable program or batch file.

**Comment by t-shreysingh** [comment]
@palmerj3 @PavanMudigondaTR Could you help me out? 
Not able to produce junit.xml file using command
JEST_JUNIT_OUTPUT_NAME="file.xml" jest
Error: 'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command,
operable program or batch file.

**Comment by PavanMudigondaTR** [comment]
> @palmerj3 @PavanMudigondaTR Could you help me out? Not able to produce junit.xml file using command JEST_JUNIT_OUTPUT_NAME="file.xml" jest Error: 'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command, operable program or batch file.

provide your full command that you used and version number of package !

**Comment by t-shreysingh** [comment]
I have used this command to create junit.xml and it is successfully creating junit.xml file
>**jest --ci --reporters=default --reporters=jest-junit**
But when I'm using this command to create a junit file with different name it is giving me an error. The command is
>**JEST_JUNIT_OUTPUT_NAME="file.xml" jest**
error: 'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command,
operable program or batch file.
The version of jest is: 27.3.1
"jest-junit": "^16.0.0"
@PavanMudigondaTR

**Comment by t-shreysingh** [comment]
@PavanMudigondaTR pls help me out? I have provided the command in above comment.

**Comment by PavanMudigondaTR** [comment]
try below command @t-shreysingh 

JEST_JUNIT_OUTPUT_NAME="file.xml" jest --ci --reporters=default --reporters=jest-junit

**Comment by t-shreysingh** [comment]
C:\Users\t-shreysingh\Downloads\jestfile-2\JEST(COPY)>JEST_JUNIT_OUTPUT_NAME="file.xml" jest --ci --reporters=default --reporters=jest-junit
'JEST_JUNIT_OUTPUT_NAME' is not recognized as an internal or external command,
operable program or batch file. @PavanMudigondaTR

**Comment by t-shreysingh** [comment]
I figured out. 
This command is working
set JEST_JUNIT_OUTPUT_NAME=file.xml && npx jest --ci --reporters=default --reporters=jest-junit
Thank you @PavanMudigondaTR for the response
