### ISSUE TITLE
[Question] include console log as a system.out to the junit report.

### ISSUE THREAD

**Issue by ievgennaida** [jest-community/jest-junit#223]
Junit format is supporting next XML nodes to keep the logs and evidences/errors of the tests execution:

```
- <system-out></system-out>
- <system-err></system-err>
```

Do you have any way to configure plugin to include console output for the jUnit?
BR.

**Comment by palmerj3** [comment]
jest-junit does support it but jest itself no longer sends reporters this data as of many major versions ago.

More details here https://github.com/jest-community/jest-junit/issues/45
