### ISSUE TITLE
Handle boolean values in addition to strings within config

### ISSUE THREAD

**Issue by AndreasHae** [jest-community/jest-junit#225]
I lost a lot of time trying to configure unique output names because I was passing the `uniqueOutputName` parameter as `true` (boolean) instead of `"true"` (string). Only after manually checking the project's source code, I found that it only checks for strings. That's a major footgun when configuring directly using jest.config.js. Seems like an easy fix as well.

I'm using version 14.0.1.

**Comment by palmerj3** [comment]
It's not an easy fix unless we remove the ability to configure jest-junit via environment variables. A lot of teams are dependent on this functionality so this is why we have a not ideal ergonomics here.

Always open to better docs or for someone to magically fix this with a PR.

**Comment by AndreasHae** [comment]
I think there's a misunderstanding. I don't want to replace the existing option to be configured by the string `"true"`, I just want to extend it to also allow using the boolean `true`. This should not break environment variables.
