### ISSUE TITLE
jest-junit incorrectly merges 2 test suites

### ISSUE THREAD

**Issue by phalgunv** [jest-community/jest-junit#245]
Minimal reproducible example: https://github.com/phalgunv/jest-junit

In the above repo, sum.test.js contains 2 `describe()` blocks - for addition and subtraction. However in the junit.xml, there is single `<testsuite>` tag for addition.  This is resulting in test cases being reported incorrectly. 

Actual 
```
  <testsuite name="addition" errors="0" failures="0" skipped="0" timestamp="2023-03-07T19:31:04" time="0.262" tests="2">
    <testcase classname="addition positive numbers should add up" name="addition positive numbers should add up" time="0.002">
    </testcase>
    <testcase classname="subtraction positive numbers should subtract" name="subtraction positive numbers should subtract" time="0">
    </testcase>
  </testsuite>
```

Expected:
```
  <testsuite name="addition" errors="0" failures="0" skipped="0" timestamp="2023-03-07T19:31:04" time="0.262" tests="1">
    <testcase classname="addition positive numbers should add up" name="addition positive numbers should add up" time="0.002">
    </testcase>
  </testsuite>

<testsuite name="subtraction" errors="0" failures="0" skipped="0" timestamp="2023-03-07T19:31:04" time="0.262" tests="1">
    <testcase classname="subtraction positive numbers should subtract" name="subtraction positive numbers should subtract" time="0">
    </testcase>
</testsuite>
```

Can the expected result be achieved by configuration ?

**Comment by palmerj3** [comment]
Thanks for submitting an issue!

I think the confusion here is that Jest actually considers each test file a suite, not each describe block. So this is how jest-junit represents things.

You can absolutely have multiple describe blocks per file and even nest them as you have done here. jest-junit can use those describe block names in various places based on your configuration.

Here is how your test looks to jest-junit. You can see jest iterates through the tests not the describe blocks.

`{
  "numFailedTestSuites": 0,
  "numFailedTests": 0,
  "numPassedTestSuites": 1,
  "numPassedTests": 2,
  "numPendingTestSuites": 0,
  "numPendingTests": 0,
  "numRuntimeErrorTestSuites": 0,
  "numTodoTests": 0,
  "numTotalTestSuites": 1,
  "numTotalTests": 2,
  "openHandles": [],
  "snapshot": {
    "added": 0,
    "didUpdate": false,
    "failure": false,
    "filesAdded": 0,
    "filesRemoved": 0,
    "filesRemovedList": [],
    "filesUnmatched": 0,
    "filesUpdated": 0,
    "matched": 0,
    "total": 0,
    "unchecked": 0,
    "uncheckedKeysByFile": [],
    "unmatched": 0,
    "updated": 0
  },
  "startTime": 1678243830484,
  "success": false,
  "testResults": [
    {
      "leaks": false,
      "numFailingTests": 0,
      "numPassingTests": 2,
      "numPendingTests": 0,
      "numTodoTests": 0,
      "openHandles": [],
      "perfStats": {
        "end": 1678243831136,
        "runtime": 506,
        "slow": false,
        "start": 1678243830630
      },
      "skipped": false,
      "snapshot": {
        "added": 0,
        "fileDeleted": false,
        "matched": 0,
        "unchecked": 0,
        "uncheckedKeys": [],
        "unmatched": 0,
        "updated": 0
      },
      "testFilePath": "/Users/jsonp/Desktop/test/__tests__/sum.test.js",
      "testResults": [
        {
          "ancestorTitles": [
            "addition",
            "positive numbers"
          ],
          "duration": 2,
          "failureDetails": [],
          "failureMessages": [],
          "fullName": "addition positive numbers should add up",
          "invocations": 1,
          "location": null,
          "numPassingAsserts": 1,
          "retryReasons": [],
          "status": "passed",
          "title": "should add up"
        },
        {
          "ancestorTitles": [
            "subtraction",
            "positive numbers"
          ],
          "duration": 0,
          "failureDetails": [],
          "failureMessages": [],
          "fullName": "subtraction positive numbers should subtract",
          "invocations": 1,
          "location": null,
          "numPassingAsserts": 1,
          "retryReasons": [],
          "status": "passed",
          "title": "should subtract"
        }
      ],
      "failureMessage": null
    }
  ],
  "wasInterrupted": false
}`

**Comment by phalgunv** [comment]
Thanks @palmerj3 

From what I understand each test file must contain only one top-level `describe()` block. Is there any workaround so that I can avoid updating the test file?

**Comment by palmerj3** [comment]
Sorry there is not

**Comment by palmerj3** [comment]
Jest passes reporters who listen for the onTestResult event AggregatedResultWithoutCoverage[AggregatedResultWithoutCoverage](https://github.com/jestjs/jest/blob/main/packages/jest-test-result/src/types.ts#L54) .

This type contains the testResults property of type TestResult[TestResult](https://github.com/jestjs/jest/blob/main/packages/jest-test-result/src/types.ts#L90).

Each index in TestResult has a testFilePath and aggregate reporting results such as numFailingTests, numPassingTests, etc which map exactly to Junit TestSuite level reporting.

Hence, Jest treats test files as suites.

I've worked on the reporter system enough to go into more detail if needed but this should suffice.

**Comment by palmerj3** [comment]
Jest does not give the ability for reporters to easily iterate through describe blocks recursively so even if you wanted a reporter to treat describe blocks as test suites it would be an error-prone, edge case heavy, pain.

I am very willing to accept pull requests if you wanted to give it a shot.

**Comment by phalgunv** [comment]
Thanks @palmerj3! If it is Jest that is causing the pain, I guess it would be better if an issue is raised to Jest project to make it easier for reporters to be able treat describe block as test suites. However, I do not know enough to be able to suggest changes in Jest. Would you help raising an issue with Jest, if you agree?

**Comment by phalgunv** [comment]
I see jest-html-reporter and jest-html-reporters(in particular) are able to display the `describe()` blocks under the file name as I would expect it to be. But I do not know how they're able to do it.

jest-html-reporter:
![image](https://user-images.githubusercontent.com/10145093/235250521-c711c923-7009-412f-b7b0-2f7c1cb088e3.png)

jest-html-reporters:
![image](https://user-images.githubusercontent.com/10145093/235250732-8e82ed40-6433-48d0-9df9-3d41d86704ce.png)
