### ISSUE TITLE
Feature request: attribute retry

### ISSUE THREAD

**Issue by caionakai** [jest-community/jest-junit#254]
Hi,

I would like to propose a new feature that facilitates easy access to an attribute which tracks the number of retries for each test case. Or is there any straightforward way already implemented to retrieve this information?

**Comment by palmerj3** [comment]
jest-junit follows the jenkins XSD for junit so this attribute is not a standard offering.

If you have access to this information you can utilize the testCasePropertiesFile feature which would enable you to add non-standard test case property tags containing information like this.
