### ISSUE TITLE
Code Coverage not included in JUnit Report

### ISSUE THREAD

**Issue by habtim** [jest-community/jest-junit#263]
Cheers,

I want to track the code coverage of our applications via jest and want to propagate them to junit.
I found several hints how to do this on the web, e.g. https://elisegev.medium.com/running-tests-and-creating-code-coverage-reports-for-react-nodejs-project-continuously-with-60312b6a2dd0 or https://stackoverflow.com/questions/55002587/is-there-a-way-to-generate-jest-istanbul-coverage-report-in-junit-xml-format

Unfortunately, none of theire approaches worked for me.
I created a [minimal reproduction repo](https://github.com/habtim/test-jest-junit-coverage/)

I don't want to rely on different packages, such as cobertura. As mentioned before, this seems to be working with junit only already.

**Comment by palmerj3** [comment]
Hey!

So both of those articles are incorrect.

junit.xml files contain no references to code coverage at all. Junit files tell you which tests were executed, how long they took, and whether they passed/failed/errored/skipped.

They don't say how many lines or branches the tests covered. For that you need to enable code coverage (e.g. cobertura) and jest generates a separate coverage file that your CI can recognize.

**Comment by habtim** [comment]
Thanks for your fast response!
As jest already offers code coverage reports, I assumed it could be handed to junit as well.
Thanks for pointing this out.
