### ISSUE TITLE
testsuite.timestamp is in UTC, should be in local

### ISSUE THREAD

**Issue by dalle** [jest-community/jest-junit#43]
According to JUnit `testsuite.timestamp` is expected to be in local time without any timezone indicator (yes, it is strange indeed, but never the less).

**Comment by palmerj3** [comment]
@dalle ah weird.. I would much prefer UTC. Is this causing a problem for you?

Looking at the spec I'm not seeing where it says it needs local. Just that it needs to be ISO8601_DATETIME_PATTERN compatible.

**Comment by ccarpita** [comment]
From the Ant dev mailing list I found the closest thing to a format spec:

http://ant.1045680.n5.nabble.com/schema-for-junit-xml-output-td1375274.html

In this definition, `timestamp` should be `xsd:dateTime`, which may optionally include a timezone:

http://www.datypic.com/sc/xsd/t-xsd_dateTime.html

**Comment by dalle** [comment]
@palmerj3 I would also prefer that JUnit would expect it to be in UTC. In the end it's not causing any real problems which cannot be ignored. The tests are just reported to be run at an incorrect time, of which the time is just an offset depending on the current timezone.

**Comment by agalpin** [comment]
Jenkins junit plugin appears to require it in local else you get the following error message.
This is when the local time is set to a time zone that is say +8 - +13

> Test reports were found but none of them are new. Did leafNodes run? 
> 
> For example, /var/jenkins/workspace/blah/blah/blah/junit_editor_iOS.xml is 12 hr old

**Comment by torarnv** [comment]
> Looking at the spec I'm not seeing where it says it needs local. Just that it needs to be ISO8601_DATETIME_PATTERN compatible.

Drive-by note while investigating similar issues in another framework: The ISO8601 spec seems to mandate local time for unqualified time: https://en.wikipedia.org/wiki/ISO_8601#Local_time_(unqualified)
