### ISSUE TITLE
Reporter is not a constructor - error

### ISSUE THREAD

**Issue by assafushy** [jest-community/jest-junit#58]
hi,
tried to add the package as explained getting this error :

![image](https://user-images.githubusercontent.com/7502687/42127446-84c59fcc-7ca1-11e8-9863-294ea7301a7d.png)

this is my pachage.json with the jest config:

![image](https://user-images.githubusercontent.com/7502687/42127451-a8b134b4-7ca1-11e8-9525-a293cda6866d.png)

help anyone?

**Comment by palmerj3** [comment]
@assafushy hey! Sorry about that.

Can you just give me some more details?

Specifically I'm gonna need your OS, node version, jest-junit version, and jest version.

Thanks

**Comment by assafushy** [comment]
hi thnks...

windows 10
node 8.11.1
 "jest": "^23.2.0",
"jest-junit": "^4.0.0"

**Comment by palmerj3** [comment]
@assafushy so the issue is that you're using jest-junit 4.x and that version still relied on it being used as a testResultsProcessor.

You'll need to upgrade to version 5.x in order to use jest-junit as a jest reporter.

**Comment by assafushy** [comment]
thanks a lot  - i upgraded and ran. 
now i get this error at the end of the run 
![image](https://user-images.githubusercontent.com/7502687/42133272-fb0d3f4e-7d2f-11e8-97a5-6fb8d0ade932.png)

**Comment by assafushy** [comment]
updated the depracted command.
still get the max call stack error

**Comment by palmerj3** [comment]
I can't reproduce that so I think that's most likely an error on your end.

One thing to try: remove the "<rootDir>/junit.xml". jest-junit currently doesn't support the "rootDir" syntax that jest does. It likely will in future versions but it currently does not. So windows might be having an issue creating a directory name like that.

**Comment by palmerj3** [comment]
Googling is probably your best option for that. i'm not super familiar with jenkins.
https://jenkins-le-guide-complet.github.io/html/sect-first-steps-metrics.html
