### ISSUE TITLE
Templated output

### ISSUE THREAD

**Issue by Vivalldi** [jest-community/jest-junit#61]
It would be great if we could template the name of the output file.

That way projects that utilize yarn workspaces can set a single output dir with changing titles
```
"jest-junit": {
    "output": "./test-{title}.xml",
  }
```

**Comment by palmerj3** [comment]
Cool idea!

Do you see this as being workspace-specific or something that could be used more generally in systems like lerna?

Feel free to submit a PR!

**Comment by Vivalldi** [comment]
I don't think it would be workspace specific. Definitely something that could be used by learn or even someone who has a custom way oh managing a monorepo. While tinkering around with the idea I thought of something else that might go along with this/be a better option.

Implement a `JEST_JUNIT_OUTPUT_DIR` and a `fileName` option that allows for multiple suites to be run using a single output directory but with various names at the same time.

**Comment by Vivalldi** [comment]
I can play around with the `OUTPUT_DIR` idea some this weekend.
