### ISSUE TITLE
Jest configuration are not currently supported by Create React App:    • testResultsProcessor

### ISSUE THREAD

**Issue by QuantumInformation** [jest-community/jest-junit#63]
If we add

```
{
  "testResultsProcessor": "jest-junit"
}
```
we get this

Out of the box, Create React App only supports overriding these Jest options:

  • collectCoverageFrom
  • coverageReporters
  • coverageThreshold
  • snapshotSerializers.

These options in your package.json Jest configuration are not currently supported by Create React App:

  • testResultsProcessor

**Comment by seniorquico** [comment]
I added the following configuration block to our create-react-app@2 project's `package.json` file:

```json
{
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!src/**/*.d.ts",
      "!src/**/__stories__/",
      "!<rootDir>/node_modules/"
    ],
    "coverageReporters": [
      "jest-junit"
    ]
  }
}
```

Unfortunately, that fails with the following error:

```sh
$ yarn run test --coverage
      Failed to write coverage reports:
      ERROR: Error: Invalid report format [jest-junit]
      STACK: Error: Invalid report format [jest-junit]
  at Object.module.exports.create (D:\Users\username\Documents\Project\node_modules\istanbul-api\lib\input-error.js:6:15)
  at Reporter.add (D:\Users\username\Documents\Project\node_modules\istanbul-api\lib\reporter.js:51:30)
  at D:\Users\username\Documents\Project\node_modules\istanbul-api\lib\reporter.js:62:18
  at Array.forEach (<anonymous>)
  at Reporter.addAll (D:\Users\username\Documents\Project\node_modules\istanbul-api\lib\reporter.js:61:14)
  at D:\Users\username\Documents\Project\node_modules\jest-cli\build\reporters\coverage_reporter.js:180:18
  at Generator.next (<anonymous>)
  at step (D:\Users\username\Documents\Project\node_modules\jest-cli\build\reporters\coverage_reporter.js:75:30)
  at D:\Users\username\Documents\Project\node_modules\jest-cli\build\reporters\coverage_reporter.js:86:15
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

Our test suite runs just fine with `yarn run test`, but obviously produces no coverage. I also tried the example CI command from the README:

```sh
$ jest --ci --reporters=default --reporters=jest-junit
```

That produces a `junit.xml` file, but it yields incorrect results due to the missing Jest configs loaded by create-react-app (for example, none of our `.env` files get loaded).

Has anyone successfully configured jest-junit in a create-react-app@2 project?

**Comment by seniorquico** [comment]
D'oh! I wasn't paying close enough attention... my mistake was dropping jest-junit into `coverageReporters` (as opposed to `reporters`).

Echoing OP, create-react-app@2 does not support a custom `reporters` configuration in `package.json`. Interestingly, both of the following commands work:

```sh
$ yarn run test --ci --coverage --reporters=default --reporters=jest-junit
$ yarn run test --ci --coverage --testResultsProcessor=jest-junit
```

I didn't think create-react-app allowed options to be specified on the command line. Oh well, I get the desired `junit.xml` file (along with the deprecation notice for the second command).

**Comment by QuantumInformation** [comment]
Yeah I don't like the  deprecation notice

**Comment by palmerj3** [comment]
CRA is very limiting with the configurations it allows folks to override. That's out of the control of jest-junit.

jest-junit is a reporter so it needs to be used that way. I would say if CRA isn't supporting jest-junit properly for you as-is then eject. It seems to work fine within Spotify with any CRA-based app.

**Comment by ankitkadali** [comment]
> For future reference, the following configuration in our CRA-based app's `package.json` is working great:
> 
> ```json
>   "scripts": {
>     "test:ci": "react-scripts test --ci --coverage --reporters=default --reporters=jest-junit"
>   }
> ```

i am using this configuration in my package.json file. But while i add jest-junit key in the package.json file to configure testsuiteName in the junit.xml file; the xml still uses default describe string rather it should use the filepath
  "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test --env=jsdom",
        "test:cov": "yarn test -- --coverage",
        "test:ci": "react-scripts test --env=jsdom --reporters=jest-junit ./node_modules/jest-junit --coverage ",
        "eject": "react-scripts eject",
        "lint": "eslint src",
        "dev": "node server & react-scripts start",

        "jest-junit": {
          "reporters":["jest-junit"],
           "output": "./junit.xml",
           "classNameTemplate": "{classname}-{title}",
           "titleTemplate": "{classname}-{title}",
           "ancestorSeparator": " › ",
           "suiteNameTemplate": "{filepath}",
           "usePathForSuiteName": "true"
       }
    },

**Comment by ClydeDz** [comment]
Just adding something that worked for me. 

Install the npm package `jest-junit`. Then execute `npm run test:ci` with the following scripts in the `package.json` file. It will produce a `junit.xml` file along with test coverage report files inside the coverage folder. 

```
"scripts": {
    "test": "react-scripts test",
    "test:ci":"npm run test -- --coverage --ci --testResultsProcessor=\"jest-junit\""
},
```
