### ISSUE TITLE
Not working with projects?

### ISSUE THREAD

**Issue by rattrayalex-stripe** [jest-community/jest-junit#68]
Hi, 

Jest now has the ability to specify multiple projects: https://jestjs.io/docs/en/configuration.html#projects-array-string-projectconfig

When I try to use this with jest-junit, I don't seem to have any junit files generated. No errors are thrown.

As a workaround, I'm running each project separately in CI with `--config` settings, eg; 

```
// package.json: 
"jest": {
  "projects": ["foo.jest.config.js", "bar.jest.config.js"]
}

// ci script: 
JEST_JUNIT_OUTPUT=foo-tests.xml yarn jest --config foo.jest.config.js
JEST_JUNIT_OUTPUT=bar-tests.xml yarn jest --config bar.jest.config.js

// in development
yarn jest // runs both foo and bar
```

I haven't done any digging into why this may be happening. 

Do you think this can be fixed?

**Comment by SimenB** [comment]
I think this is related to https://github.com/facebook/jest/issues/5441

**Comment by rattrayalex-stripe** [comment]
Seems pretty plausible; thanks @SimenB .  Looks like that's been aging for a while without a concrete plan for action; sounds a little tricky.

**Comment by palmerj3** [comment]
jest-junit itself does not rely on globalSetup or globalTeardown. But reporters are configured globally, not on a per-project basis. So I would suggest having a top level jest config that specifies the projects and the reporter(s) you want to use. Or specify the reporters via cli args.

At Spotify jest-junit is used widely with multiple project jest configurations.
