### ISSUE TITLE
Jenkins test result report broken after upgrading to v6

### ISSUE THREAD

**Issue by nicolasschabram** [jest-community/jest-junit#74]
After upgrading to [v6](https://github.com/jest-community/jest-junit/releases/tag/v6.0.0), Jenkins/xUnit fail to read the test result reports (complaining about the `file` attribute in `testcase`):

> WARNING: At line 3 of file:/var/lib/jenkins/workspace/[...]/target/junit.xml:cvc-complex-type.3.2.2: Attribut 'file' darf nicht in Element 'testcase' vorkommen.
> [...]
> FATAL: The result file '/var/lib/jenkins/workspace/[...]/target/junit.xml' for the metric 'JUnit' is not valid. The result file has been skipped.

I guess it has to do with https://github.com/jest-community/jest-junit/pull/71.

Anyone else experiencing this problem?

---

Jenkins: v2.150.1
xUnit plugin: v.2.3.2

**Comment by palmerj3** [comment]
@nicolasschabram thanks for reporting. I may roll back that change if it's broken on jenkins. For now please use v5 but I'm going to leave this issue open for a bit to see if others hit this problem.

**Comment by palmerj3** [comment]
Hey @nicolasschabram I have rolled back this change and published 6.0.1. Would you please test out this version on your pipeline and let me know if it works?

**Comment by nicolasschabram** [comment]
It does, thank you very much! @palmerj3

**Comment by palmerj3** [comment]
@nicolasschabram cool I will close this. If you don't mind I will ping you in the next few days when we re-add this functionality as a configuration option. It's always useful if I have some folks that can test it in their environment.

**Comment by nicolasschabram** [comment]
Sure, happy to help! Thanks!
