### ISSUE TITLE
Not reading jest.config.js

### ISSUE THREAD

**Issue by Godrules500** [jest-community/jest-junit#91]
Hello, I have setup my jest to use the jest config, however jest-junit is ignoring it and using all default values. However if I add it to the package.json it works. Is there something I need to do to have it point to the jest config and not the package.json?

I copied and pasted what was in the instructions

**Comment by palmerj3** [comment]
Please provide a gist of your jest.config.js so I can see what the issue is

**Comment by Godrules500** [comment]
Nevermind! figured it out. I was using jest --ci --reporters=default --reporters=jest-junit which was probably overriding the jest.config.js settings.  Changed it to jest --ci and all works!

Amazing what a fresh start does. 30 second versus 4 hours lol.

**Comment by aaronhong** [comment]
@Godrules500 your answer helped a lot. Why does specifying the reporters on the CLI like `jest --ci --reporters=default --reporters=jest-junit` ignore the `jest.config.js` settings?
