### ISSUE TITLE
Add option to output xml to stdout

### ISSUE THREAD

**Issue by kevinbarabash** [jest-community/jest-junit#93]
I'm working on a project that has some custom tooling around running tests and being able consume junit output via stdout would make things a lot easier.  Would you be interested in a PR to add an option to send output to stdout instead of a file?

**Comment by palmerj3** [comment]
I am so sorry for not responding to this sooner!

Could you give me some more details around this? So far this is the first request I've gotten for this functionality so I'm thinking it would not be heavily used.

**Comment by kevinbarabash** [comment]
Actually I ended up not needing this.
