### ISSUE TITLE
Add Test steps to add granularity to the test report

### ISSUE THREAD

**Issue by jb-brossard** [jest-community/jest-junit#95]
I would like to know if it would be possible to add more granularity in the junit.xml report. I would like to list the test step each test need to go through. So that, in my report, i could see all the step that happen and get the context right away if there is a failure. Is this something possible ?

I try to add assertion at each steps and also just do a test for each step. But it doesn't work. In the case of the assertion it only show the failed one. And for the later one, Jest does not guarantee the order in which a test is ran within a test suite.

**Comment by palmerj3** [comment]
Hey @jb-brossard! Probably the best bet would be to include more output in the generated xml files.

One path you can take is enabling console support via the "includeConsoleOutput" option.

Aside from that that's about the best the junit spec can offer - it's really a format more for giving you information about what tests passed/failed and not much more.

**Comment by jb-brossard** [comment]
Hey @palmerj3  thank you for the quick answer, I am trying the option includeConsoleOutput, But i am not seeing anything in the junit.xml.   I setup in my terminal: `JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT="true"` and I tried on the package.json:

```
  "jest-junit": {
      "includeConsoleOutput": "true"
  }
```
Also, I came across this post : 
https://stackoverflow.com/questions/46496723/adding-metadata-to-testdroids-junit-xml

and it seem they are adding properties.

**Comment by palmerj3** [comment]
Yeah junit.xml properties is another way to go. They are generic key value pairs that you can use. But there isn't a great use-case for them in jest-junit since it would need to apply to everyone.

If you do end up adding properties what I would suggest is decorating the junit.xml that jest-junit generates and add properties to it.

**Comment by palmerj3** [comment]
@jb-brossard please try jest-junit version 7.0.0 (just published yesterday) to include console support. You'll need to have at least 2 tests and not use verbose mode in jest. Going to close this issue for now.
