### ISSUE TITLE
Shorten output of the newly implemented console logging junit xml

### ISSUE THREAD

**Issue by cisum-la** [jest-community/jest-junit#97]
Recently console logging was implemented as part of 7.0.0 , We really like this feature and are about to add it to our test suite. However, we noticed that currently the logged object is unnecessarily long with redundant info, see below:
{
    "message": "2019-07-31 15:02:50:360 WorkerID:1 \u001b[32minfo\u001b[39m: Generated headers for account \n",
    "origin": "/Users/s/Documents/dev/qa-automation/node_modules/winston/lib/winston/transports/console.js:79",
    "type": "log"
  }

Instead it would be nice if only the message value is displayed in the logs, see below:
"2019-07-31 15:00:53:930 WorkerID:1 \u001b[32minfo\u001b[39m: Generated headers\n",

Another option would be provide a way to switch between the two options,e.g. full_console_log = true/false in jest-junit in case the full form has benefit for other users.  I was able to get the shorttened logs by changing below line 77 in [index.js](https://github.com/jest-community/jest-junit/blob/7b900759f9ed9dde1857ccb440fad9d0a7f374ee/index.js#L77) 
` consoleBuffer[testResult.testFilePath] = testResult.console.map(item => item.message) `
The shorter logging also has the benefit of smaller log file.

Appreciate any thoughts on the above.

**Comment by palmerj3** [comment]
Hello! I would be open to there being an additional option that shows a shortened output possibly.

Would you want to submit a PR to add this?

**Comment by cisum-la** [comment]
Thanks for your quick response! Yes, will create a PR with a new environment and config variable respectively in the next few days which includes the above discussed change:

JEST_JUNIT_INCLUDE_SHORT_CONSOLE_OUTPUT | includeShortConsoleOutput

**Comment by palmerj3** [comment]
Thanks!

**Comment by cisum-la** [comment]
On further investigation - it turned out that in the case of Winston logger + jest (that we use internally here), the 'origin' key is always same -   "/Users/s/Documents/dev/qa-automation/node_modules/winston/lib/winston/transports/console.js:79", but when we use regular console logger then the origin key correctly lists the file:line_number where the console.log was used. I have reported this issue to Jest: https://github.com/facebook/jest/issues/8790 and based on the outcome there will create a PR here if needed.

**Comment by palmerj3** [comment]
Ah ok - thanks for the update!
