### ISSUE TITLE
Configure directory for output xml file?

### ISSUE THREAD

**Issue by basickarl** [jest-community/jest-junit#98]
I'm just curious, I can't find any examples or documentation on how to output the generated test-results.xml to a specific directory. Is this possible?

**Comment by palmerj3** [comment]
The third option in the [configuration table list](https://github.com/jest-community/jest-junit#configuration). JEST_JUNIT_OUTPUT_DIR, outputDirectory.

**Comment by basickarl** [comment]
@palmerj3 Oh. My. God. What a miss on my  behalf, so sorry!

**Comment by steve-taylor** [comment]
Does it not also work as a command line option?

e.g.

```
jest --ci \
  --reporters=default \
  --reporters=jest-junit \
  --outputDirectory=tmp
```
