### ISSUE TITLE
How to let the report contain screenshot been taken by puppeteer?

### ISSUE THREAD

**Issue by adamchenwei** [jest-community/jest-junit#99]
or even the screenshot taken at the end of each test / test failure?
Assume the screenshot already been taken by puppeteer...
I am not really sure if its something has to been done inside jest or somewhere else?

Thanks

**Comment by palmerj3** [comment]
To be compliant with all junit spec's you would have to include a property to the testsuite. There are no properties for each test case so you wouldn't be able to associate a link to an image with each test case..

Therefore I don't think that's appropriate functionality to live in jest-junit.

**Comment by adamchenwei** [comment]
@palmerj3 I try to use Allure to load the junit report generated by jest-junit. Would you have any idea on how the end of test image snapshot wire into Allure reading the junit report generated by this library has anything to do with junit spec or its more of an Allure specialty?

**Comment by palmerj3** [comment]
@adamchenwei I don't know the answer to that but let me see if one of my colleagues does. I'll see if they can comment on this because I know they use a very similar testing stack. Hang tight.

**Comment by jaysirju** [comment]
The allure modules has methods to attach screenshots to the report itself.  If you are using the [jest-allure](https://github.com/zaqqaz/jest-allure) module, you can call reporter.addAttachment() from the test code itself.
`            const screenshotBuffer = await page.screenshot();
            reporter.addAttachment("Screenshot", screenshotBuffer, "image/png");`

**Comment by honsa** [comment]
How can we add a screenshot with jest-junit?

The solution above uses another plugin.

**Comment by palmerj3** [comment]
The junit spec doesn't allow for binary attachments.

What you could do is upload the screenshots somewhere and then reference them in properties (which are now supported in jest-junit).

But jest-junit is not going to natively support screenshots or any kind of artifacts. junit.xml is itself an artifact.

**Comment by honsa** [comment]
We just need the link in the junit report, binary can be handled separate

`<testcase time="1.00" name="Test">
  <system-out>[[ATTACHMENT|/absolute/path/to/some/file]]</system-out>
</testcase>`

**Comment by palmerj3** [comment]
system-out right now is only populated by stdout and jest itself has, as of a few releases ago, stopped sending stdout data to reporters like jest-junit. So it's possible if you use an older version of jest.

But right now there is no hook in jest-junit to add output to system-out directly.
